package com.dhivya.code.playground;

public class PL08KeyWords {

	public static final String ABSTRACT = "Java abstract keyword is used to declare an abstract class. "
			+ "An abstract class can provide the implementation of the interface. It can have abstract and non-abstract methods.";
	public static final String BOOLEAN = "Java boolean keyword is used to declare a variable as a boolean type. It can hold True and False values only.";
	public static final String BREAK = "Java break keyword is used to break the loop or switch statement."
			+ " It breaks the current flow of the program at specified conditions.";
	public static final String BYTE = "Java byte keyword is used to declare a variable that can hold 8-bit data values.";
	public static final String CASE = "Java case keyword is used with the switch statements to mark blocks of text.";
	public static final String CATCH = "Java catch keyword is used to catch the exceptions generated by try statements. "
			+ "It must be used after the try block only.";
	public static final String CHAR = "Java char keyword is used to declare a variable that can hold unsigned 16-bit Unicode characters";
	public static final String CLASS = "Java class keyword is used to declare a class.";
	public static final String CONTINUE = "Java continue keyword is used to continue the loop. "
			+ "It continues the current flow of the program and skips the remaining code at the specified condition.";
	public static final String DEFAULT = "Java default keyword is used to specify the default block of code in a switch statement.";
	public static final String DO = "Java do keyword is used in the control statement to declare a loop. "
			+ "It can iterate a part of the program several times.";
	public static final String DOUBLE = "Java double keyword is used to declare a variable that can hold 64-bit floating-point number.";
	public static final String ELSE = "Java else keyword is used to indicate the alternative branches in an if statement.";
	public static final String ENUM = "Java enum keyword is used to define a fixed set of constants. "
			+ "Enum constructors are always private or default.";
	public static final String EXTENDS = "Java extends keyword is used to indicate that a class is derived from another class or interface.";
	public static final String FINAL = "Java final keyword is used to indicate that a variable holds a constant value. "
			+ "It is used with a variable. It is used to restrict the user from updating the value of the variable.";
	public static final String FINALLY = "Java finally keyword indicates a block of code in a try-catch structure. "
			+ "This block is always executed whether an exception is handled or not.";
	public static final String FLOAT = "Java float keyword is used to declare a variable that can hold a 32-bit floating-point number.";
	public static final String FOR = "Java for keyword is used to start a for loop. "
			+ "It is used to execute a set of instructions/functions repeatedly when some condition becomes true. If the number of iteration is fixed,"
			+ " it is recommended to use for loop.";
	public static final String IF = "Java if keyword tests the condition. "
			+ "It executes the if block if the condition is true.";
	public static final String IMPLEMENTS = "Java implements keyword is used to implement an interface.";
	public static final String IMPORT = "Java import keyword makes classes and "
			+ "interfaces available and accessible to the current source code.";
	public static final String INSTANCEOF = "Java instanceof keyword is used to test whether the object is an "
			+ "instance of the specified class or implements an interface.";
	public static final String INT = "Java int keyword is used to declare a variable that can hold a 32-bit signed integer.";
	public static final String INTERFACE = "Java interface keyword is used to declare an interface. It can have only abstract methods.";
	public static final String LONG = "Java long keyword is used to declare a variable that can hold a 64-bit integer.";
	public static final String NATIVE = "Java native keyword is used to specify that a method is implemented in native code using JNI (Java Native Interface).";
	public static final String NEW = "Java new keyword is used to create new objects.";
	public static final String NULL = "Java null keyword is used to indicate that a reference does not refer to anything. It removes the garbage value.";
	public static final String PACKAGE = "Java package keyword is used to declare a Java package that includes the classes.";
	public static final String PRIVATE = "Java private keyword is an access modifier. It is used to indicate that a method or "
			+ "variable may be accessed only in the class in which it is declared.";
	public static final String PROTECTED = "Java protected keyword is an access modifier. It can be accessible within the package "
			+ "and outside the package but through inheritance only. It can't be applied with the class.";
	public static final String PUBLIC = "Java public keyword is an access modifier. It is used to indicate that an item is accessible "
			+ "anywhere. It has the widest scope among all other modifiers.";
	public static final String RETURN = "Java return keyword is used to return from a method when its execution is complete.";
	public static final String SHORT = "Java short keyword is used to declare a variable that can hold a 16-bit integer.";
	public static final String STATIC = "Java static keyword is used to indicate that a variable or method is a class method. "
			+ "The static keyword in Java is mainly used for memory management.";
	public static final String STRICTFP = "Java strictfp is used to restrict the floating-point calculations to ensure portability.";
	public static final String SUPER = "Java super keyword is a reference variable that is used to refer to parent class objects. "
			+ "It can be used to invoke the immediate parent class method.";
	public static final String SWITCH = "The Java switch keyword contains a switch statement that executes code based on test value. "
			+ "The switch statement tests the equality of a variable against multiple values.";
	public static final String SYNCHRONIZED = "Java synchronized keyword is used to specify the critical sections or methods in multithreaded code.";
	public static final String THIS = "Java this keyword can be used to refer the current object in a method or constructor.";
	public static final String THROW = "The Java throw keyword is used to explicitly throw an exception. "
			+ "The throw keyword is mainly used to throw custom exceptions. It is followed by an instance.";
	public static final String THROWS = "The Java throws keyword is used to declare an exception."
			+ " Checked exceptions can be propagated with throws.";
	public static final String TRANSIENT = "Java transient keyword is used in serialization. "
			+ "If you define any data member as transient, it will not be serialized.";
	public static final String TRY = "Java try keyword is used to start a block of code that will be tested for exceptions. "
			+ "The try block must be followed by either catch or finally block.";
	public static final String VOID = "Java void keyword is used to specify that a method does not have a return value.";
	public static final String VOLATILE = "Java volatile keyword is used to indicate that a variable may change asynchronously.";
	public static final String WHILE = "Java while keyword is used to start a while loop. "
			+ "This loop iterates a part of the program several times. If the number of iteration is not fixed, it is recommended to use the while loop.";
}
